os: Visual Studio 2015

init:
  - git config --global core.autocrlf input

environment:
  matrix:
    - BUILD_TARGET: CreatePackage
    
build_script:
  - cmd: dotnet --version
  - cmd: build.cmd %BUILD_TARGET%

test: off
version: '{build}'
artifacts:
  - path: bin\*.nupkg
