init:
  - git config --global core.autocrlf input

environment:
  CLI_VERSION: 1.0.0-rc2-002678
  #CLI_VERSION: Latest
  matrix:
    - BUILD_TARGET: DotnetCliTests
    - BUILD_TARGET: NuGet

matrix:
  allow_failures:
    - BUILD_TARGET: DotnetCliTests

install:
  # Download install script to install .NET cli in .dotnet dir
  - ps: mkdir -Force ".\scripts\obtain\" | Out-Null
  - ps: Invoke-WebRequest "https://raw.githubusercontent.com/dotnet/cli/rel/1.0.0/scripts/obtain/install.ps1" -OutFile ".\scripts\obtain\install.ps1"
  - ps: $env:DOTNET_INSTALL_DIR = "$pwd\.dotnetcli"
  - ps: '& .\scripts\obtain\install.ps1 -Channel "preview" -version "Latest" -InstallDir "$env:DOTNET_INSTALL_DIR" -NoPath'
  # add dotnet to PATH
  - ps: $env:Path = "$env:DOTNET_INSTALL_DIR;$env:Path"
  # show dotnet info
  - ps: 'echo "Dotnet: $( (gcm dotnet).Path )"'
  - ps: dotnet --info
  
build_script:
  - cmd: build.cmd %BUILD_TARGET%

test: off
version: '{build}'
artifacts:
  - path: bin\*.nupkg
