name: Release docs

on:
  schedule:
    # Triggers the workflow every day at 17:30 UTC
    # * is a special character in YAML so you have to quote this string
    - cron:  '30 17 * * *'
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.400
    - name: Restore tools
      run: dotnet tool restore
    - name: Restore projects
      run: dotnet restore FSharp.Compiler.Service\FSharp.Compiler.Service.fsproj
    - name: Checkout fsharp master
      run: git clone https://github.com/dotnet/fsharp --depth 1 fsharp -b main
    - name: Build fsharp master (turn of CI build status)
      run: cd fsharp && eng\CIBuild.cmd -noVisualStudio
    - name: Run fsdocs
      run: dotnet fsdocs build --sourcefolder fsharp --input fsharp/docs --strict
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./output
        publish_branch: gh-pages
        force_orphan: true
